version: "3"

services:
  proxy:
    image: traefik:v2.10
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=tiernebre@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
    volumes:
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - web

  web:
    image: ${ZONE_BLITZ_WEB_DOCKER_IMAGE:-brendantierney/zone-blitz:latest}
    environment:
      ZONE_BLITZ_POSTGRES_USER: ${ZONE_BLITZ_POSTGRES_USER}
      ZONE_BLITZ_POSTGRES_PASSWORD: ${ZONE_BLITZ_POSTGRES_PASSWORD}
      ZONE_BLITZ_POSTGRES_JDBC_URL: jdbc:postgresql://${ZONE_BLITZ_POSTGRES_HOST}
      ZONE_BLITZ_OAUTH_GOOGLE_CLIENT_ID: ${ZONE_BLITZ_OAUTH_GOOGLE_CLIENT_ID}
      ZONE_BLITZ_URL: ${ZONE_BLITZ_URL}
      ZONE_BLITZ_CONTENT_SECURITY_POLICY: ${ZONE_BLITZ_CONTENT_SECURITY_POLICY}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`${ZONE_BLITZ_DOMAIN:-zoneblitz.app}`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=myresolver"
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:16
    environment:
      POSTGRES_USER: ${ZONE_BLITZ_POSTGRES_USER}
      POSTGRES_PASSWORD: ${ZONE_BLITZ_POSTGRES_PASSWORD}
      POSTGRES_DB: ${ZONE_BLITZ_POSTGRES_NAME}
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresgql/data
    labels:
      - "traefik.enable=false"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 1s
      retries: 10

  database-migration:
    image: ghcr.io/amacneil/dbmate
    environment:
      DATABASE_URL: postgres://${ZONE_BLITZ_POSTGRES_USER}:${ZONE_BLITZ_POSTGRES_PASSWORD}@${ZONE_BLITZ_POSTGRES_HOST}?sslmode=disable
    volumes:
      - ./db:/db
    command: --wait up
    depends_on:
      database:
        condition: service_healthy
