version: '3'

services:
  proxy:
    image: nginx:1
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    depends_on:
      - web

  web:
    image: brendantierney/zone-blitz:latest
