version: "3"

services:
  proxy:
    image: traefik:v2.10
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=tiernebre@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
    volumes:
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - web

  web:
    image: brendantierney/zone-blitz:latest
    environment:
      ZONE_BLITZ_POSTGRES_USER: ${ZONE_BLITZ_POSTGRES_USER}
      ZONE_BLITZ_POSTGRES_PASSWORD: ${ZONE_BLITZ_POSTGRES_PASSWORD}
      ZONE_BLITZ_POSTGRES_JDBC_URL: jdbc:postgresql://${ZONE_BLITZ_POSTGRES_HOST}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`zoneblitz.app`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=myresolver"
    depends_on:
      - database
      - database-migration

  database:
    image: postgres:16
    environment:
      POSTGRES_USER: ${ZONE_BLITZ_POSTGRES_USER}
      POSTGRES_PASSWORD: ${ZONE_BLITZ_POSTGRES_PASSWORD}
      POSTGRES_DB: ${ZONE_BLITZ_POSTGRES_NAME}
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresgql/data
    labels:
      - "traefik.enable=false"

  database-migration:
    image: ghcr.io/amacneil/dbmate
    environment:
      DATABASE_URL: postgres://${ZONE_BLITZ_POSTGRES_USER}:${ZONE_BLITZ_POSTGRES_PASSWORD}@${ZONE_BLITZ_POSTGRES_HOST}?sslmode=disable
    volumes:
      - ./db:/db
    command: --wait up
    depends_on:
      - database
