version: '3'

services:
  proxy:
    image: traefik:v2.10
    command: --api.insecure=false --providers.docker
    ports:
      # The HTTP port
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    depends_on:
      - web

  web:
    image: brendantierney/zone-blitz:latest
    labels:
      - "traefik.http.routers.web.rule=Host(`localhost`)"
