/*
 * This file is generated by jOOQ.
 */
package com.tiernebre.database.jooq;

import com.tiernebre.database.jooq.tables.Player;
import com.tiernebre.database.jooq.tables.Session;
import java.util.Arrays;
import java.util.List;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

  private static final long serialVersionUID = 1L;

  /**
   * The reference instance of <code>public</code>
   */
  public static final Public PUBLIC = new Public();

  /**
   * The table <code>public.player</code>.
   */
  public final Player PLAYER = Player.PLAYER;

  /**
   * The table <code>public.session</code>.
   */
  public final Session SESSION = Session.SESSION;

  /**
   * No further instances allowed
   */
  private Public() {
    super("public", null);
  }

  @Override
  public Catalog getCatalog() {
    return DefaultCatalog.DEFAULT_CATALOG;
  }

  @Override
  public final List<Table<?>> getTables() {
    return Arrays.asList(Player.PLAYER, Session.SESSION);
  }
}
