/*
 * This file is generated by jOOQ.
 */
package com.tiernebre.jooq.tables.records;

import com.tiernebre.jooq.tables.SchemaMigrations;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SchemaMigrationsRecord
  extends UpdatableRecordImpl<SchemaMigrationsRecord> {

  private static final long serialVersionUID = 1L;

  /**
   * Setter for <code>public.schema_migrations.version</code>.
   */
  public void setVersion(String value) {
    set(0, value);
  }

  /**
   * Getter for <code>public.schema_migrations.version</code>.
   */
  public String getVersion() {
    return (String) get(0);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  @Override
  public Record1<String> key() {
    return (Record1) super.key();
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /**
   * Create a detached SchemaMigrationsRecord
   */
  public SchemaMigrationsRecord() {
    super(SchemaMigrations.SCHEMA_MIGRATIONS);
  }

  /**
   * Create a detached, initialised SchemaMigrationsRecord
   */
  public SchemaMigrationsRecord(String version) {
    super(SchemaMigrations.SCHEMA_MIGRATIONS);
    setVersion(version);
    resetChangedOnNotNull();
  }
}
