version: "3"

services:
  proxy:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--log.level=DEBUG"
      - "--entryPoints.http.address=:80"
      - "--entryPoints.http.http.redirections.entryPoint.to=https"
      - "--entryPoints.http.http.redirections.entryPoint.scheme=https"
      - "--entryPoints.https.address=:443"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./certs:/etc/certs

  web:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ..:/workspace:cached
    labels:
      - "traefik.http.routers.web.rule=Host(`0.0.0.0`)"
      - "traefik.http.routers.web.tls=true"
      - "tls.certificates.certFile=/etc/certs/local-cert.pem"
      - "tls.certificates.keyFile=/etc/certs/local-key.pem"
