version: "3"

services:
  proxy:
    extends:
      file: ../docker-compose.common.yml
      service: proxy
    command: --api.insecure=true --providers.docker --log.level=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  web:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ..:/workspace:cached
    labels:
      - "traefik.http.routers.web.rule=Host(`0.0.0.0`)"
