version: "3"

services:
  proxy:
    extends:
      file: ../docker-compose.common.yml
      service: proxy

  web:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ..:/workspace:cached
