/*
 * This file is generated by jOOQ.
 */
package com.tiernebre.jooq;

import com.tiernebre.jooq.tables.Player;
import com.tiernebre.jooq.tables.records.PlayerRecord;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

  // -------------------------------------------------------------------------
  // UNIQUE and PRIMARY KEY definitions
  // -------------------------------------------------------------------------

  public static final UniqueKey<PlayerRecord> PLAYER_PKEY =
    Internal.createUniqueKey(
      Player.PLAYER,
      DSL.name("player_pkey"),
      new TableField[] { Player.PLAYER.ID },
      true
    );
}
