/*
 * This file is generated by jOOQ.
 */
package com.tiernebre.database.jooq.tables.records;


import com.tiernebre.database.jooq.tables.Account;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AccountRecord extends UpdatableRecordImpl<AccountRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.account.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.account.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.account.registration_id</code>.
     */
    public void setRegistrationId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.account.registration_id</code>.
     */
    public Long getRegistrationId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.account.google_account_id</code>.
     */
    public void setGoogleAccountId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.account.google_account_id</code>.
     */
    public String getGoogleAccountId() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AccountRecord
     */
    public AccountRecord() {
        super(Account.ACCOUNT);
    }

    /**
     * Create a detached, initialised AccountRecord
     */
    public AccountRecord(Long id, Long registrationId, String googleAccountId) {
        super(Account.ACCOUNT);

        setId(id);
        setRegistrationId(registrationId);
        setGoogleAccountId(googleAccountId);
        resetChangedOnNotNull();
    }
}
