/*
 * This file is generated by jOOQ.
 */
package com.tiernebre.database.jooq.tables.records;


import com.tiernebre.database.jooq.tables.GeneralManager;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GeneralManagerRecord extends UpdatableRecordImpl<GeneralManagerRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.general_manager.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.general_manager.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GeneralManagerRecord
     */
    public GeneralManagerRecord() {
        super(GeneralManager.GENERAL_MANAGER);
    }

    /**
     * Create a detached, initialised GeneralManagerRecord
     */
    public GeneralManagerRecord(Long id) {
        super(GeneralManager.GENERAL_MANAGER);

        setId(id);
        resetChangedOnNotNull();
    }
}
