/*
 * This file is generated by jOOQ.
 */
package com.tiernebre.database.jooq.tables;


import com.tiernebre.database.jooq.Keys;
import com.tiernebre.database.jooq.Public;
import com.tiernebre.database.jooq.tables.Account.AccountPath;
import com.tiernebre.database.jooq.tables.Team.TeamPath;
import com.tiernebre.database.jooq.tables.records.GeneralManagerRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GeneralManager extends TableImpl<GeneralManagerRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.general_manager</code>
     */
    public static final GeneralManager GENERAL_MANAGER = new GeneralManager();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GeneralManagerRecord> getRecordType() {
        return GeneralManagerRecord.class;
    }

    /**
     * The column <code>public.general_manager.id</code>.
     */
    public final TableField<GeneralManagerRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.general_manager.user_id</code>.
     */
    public final TableField<GeneralManagerRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.general_manager.team_id</code>.
     */
    public final TableField<GeneralManagerRecord, Long> TEAM_ID = createField(DSL.name("team_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private GeneralManager(Name alias, Table<GeneralManagerRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private GeneralManager(Name alias, Table<GeneralManagerRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.general_manager</code> table reference
     */
    public GeneralManager(String alias) {
        this(DSL.name(alias), GENERAL_MANAGER);
    }

    /**
     * Create an aliased <code>public.general_manager</code> table reference
     */
    public GeneralManager(Name alias) {
        this(alias, GENERAL_MANAGER);
    }

    /**
     * Create a <code>public.general_manager</code> table reference
     */
    public GeneralManager() {
        this(DSL.name("general_manager"), null);
    }

    public <O extends Record> GeneralManager(Table<O> path, ForeignKey<O, GeneralManagerRecord> childPath, InverseForeignKey<O, GeneralManagerRecord> parentPath) {
        super(path, childPath, parentPath, GENERAL_MANAGER);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class GeneralManagerPath extends GeneralManager implements Path<GeneralManagerRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> GeneralManagerPath(Table<O> path, ForeignKey<O, GeneralManagerRecord> childPath, InverseForeignKey<O, GeneralManagerRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private GeneralManagerPath(Name alias, Table<GeneralManagerRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public GeneralManagerPath as(String alias) {
            return new GeneralManagerPath(DSL.name(alias), this);
        }

        @Override
        public GeneralManagerPath as(Name alias) {
            return new GeneralManagerPath(alias, this);
        }

        @Override
        public GeneralManagerPath as(Table<?> alias) {
            return new GeneralManagerPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<GeneralManagerRecord, Long> getIdentity() {
        return (Identity<GeneralManagerRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<GeneralManagerRecord> getPrimaryKey() {
        return Keys.GENERAL_MANAGER_PKEY;
    }

    @Override
    public List<ForeignKey<GeneralManagerRecord, ?>> getReferences() {
        return Arrays.asList(Keys.GENERAL_MANAGER__GENERAL_MANAGER_USER_ID_FKEY, Keys.GENERAL_MANAGER__GENERAL_MANAGER_TEAM_ID_FKEY);
    }

    private transient AccountPath _account;

    /**
     * Get the implicit join path to the <code>public.account</code> table.
     */
    public AccountPath account() {
        if (_account == null)
            _account = new AccountPath(this, Keys.GENERAL_MANAGER__GENERAL_MANAGER_USER_ID_FKEY, null);

        return _account;
    }

    private transient TeamPath _team;

    /**
     * Get the implicit join path to the <code>public.team</code> table.
     */
    public TeamPath team() {
        if (_team == null)
            _team = new TeamPath(this, Keys.GENERAL_MANAGER__GENERAL_MANAGER_TEAM_ID_FKEY, null);

        return _team;
    }

    @Override
    public GeneralManager as(String alias) {
        return new GeneralManager(DSL.name(alias), this);
    }

    @Override
    public GeneralManager as(Name alias) {
        return new GeneralManager(alias, this);
    }

    @Override
    public GeneralManager as(Table<?> alias) {
        return new GeneralManager(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public GeneralManager rename(String name) {
        return new GeneralManager(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GeneralManager rename(Name name) {
        return new GeneralManager(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public GeneralManager rename(Table<?> name) {
        return new GeneralManager(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GeneralManager where(Condition condition) {
        return new GeneralManager(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GeneralManager where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GeneralManager where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GeneralManager where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GeneralManager where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GeneralManager where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GeneralManager where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GeneralManager where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GeneralManager whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GeneralManager whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
