/*
 * This file is generated by jOOQ.
 */
package com.tiernebre.database.jooq.tables;


import com.tiernebre.database.jooq.Keys;
import com.tiernebre.database.jooq.Public;
import com.tiernebre.database.jooq.tables.records.GeneralManagerRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GeneralManager extends TableImpl<GeneralManagerRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.general_manager</code>
     */
    public static final GeneralManager GENERAL_MANAGER = new GeneralManager();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GeneralManagerRecord> getRecordType() {
        return GeneralManagerRecord.class;
    }

    /**
     * The column <code>public.general_manager.id</code>.
     */
    public final TableField<GeneralManagerRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    private GeneralManager(Name alias, Table<GeneralManagerRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private GeneralManager(Name alias, Table<GeneralManagerRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.general_manager</code> table reference
     */
    public GeneralManager(String alias) {
        this(DSL.name(alias), GENERAL_MANAGER);
    }

    /**
     * Create an aliased <code>public.general_manager</code> table reference
     */
    public GeneralManager(Name alias) {
        this(alias, GENERAL_MANAGER);
    }

    /**
     * Create a <code>public.general_manager</code> table reference
     */
    public GeneralManager() {
        this(DSL.name("general_manager"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<GeneralManagerRecord, Long> getIdentity() {
        return (Identity<GeneralManagerRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<GeneralManagerRecord> getPrimaryKey() {
        return Keys.GENERAL_MANAGER_PKEY;
    }

    @Override
    public GeneralManager as(String alias) {
        return new GeneralManager(DSL.name(alias), this);
    }

    @Override
    public GeneralManager as(Name alias) {
        return new GeneralManager(alias, this);
    }

    @Override
    public GeneralManager as(Table<?> alias) {
        return new GeneralManager(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public GeneralManager rename(String name) {
        return new GeneralManager(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GeneralManager rename(Name name) {
        return new GeneralManager(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public GeneralManager rename(Table<?> name) {
        return new GeneralManager(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GeneralManager where(Condition condition) {
        return new GeneralManager(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GeneralManager where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GeneralManager where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GeneralManager where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GeneralManager where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GeneralManager where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GeneralManager where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GeneralManager where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GeneralManager whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GeneralManager whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
