/*
 * This file is generated by jOOQ.
 */
package com.tiernebre.database.jooq.tables;


import com.tiernebre.database.jooq.Keys;
import com.tiernebre.database.jooq.Public;
import com.tiernebre.database.jooq.tables.records.TeamBrandRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TeamBrand extends TableImpl<TeamBrandRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.team_brand</code>
     */
    public static final TeamBrand TEAM_BRAND = new TeamBrand();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TeamBrandRecord> getRecordType() {
        return TeamBrandRecord.class;
    }

    /**
     * The column <code>public.team_brand.id</code>.
     */
    public final TableField<TeamBrandRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    private TeamBrand(Name alias, Table<TeamBrandRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TeamBrand(Name alias, Table<TeamBrandRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.team_brand</code> table reference
     */
    public TeamBrand(String alias) {
        this(DSL.name(alias), TEAM_BRAND);
    }

    /**
     * Create an aliased <code>public.team_brand</code> table reference
     */
    public TeamBrand(Name alias) {
        this(alias, TEAM_BRAND);
    }

    /**
     * Create a <code>public.team_brand</code> table reference
     */
    public TeamBrand() {
        this(DSL.name("team_brand"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<TeamBrandRecord, Long> getIdentity() {
        return (Identity<TeamBrandRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<TeamBrandRecord> getPrimaryKey() {
        return Keys.TEAM_BRAND_PKEY;
    }

    @Override
    public TeamBrand as(String alias) {
        return new TeamBrand(DSL.name(alias), this);
    }

    @Override
    public TeamBrand as(Name alias) {
        return new TeamBrand(alias, this);
    }

    @Override
    public TeamBrand as(Table<?> alias) {
        return new TeamBrand(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TeamBrand rename(String name) {
        return new TeamBrand(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TeamBrand rename(Name name) {
        return new TeamBrand(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TeamBrand rename(Table<?> name) {
        return new TeamBrand(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TeamBrand where(Condition condition) {
        return new TeamBrand(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TeamBrand where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TeamBrand where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TeamBrand where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TeamBrand where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TeamBrand where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TeamBrand where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TeamBrand where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TeamBrand whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TeamBrand whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
