name: Deploy

on:
  push:
    branches: [ main ]

env:
  DOCKER_IMAGE: brendantierney/zone-blitz:latest
  DOCKER_NAME: zone-blitz
      
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t $DOCKER_IMAGE .
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish Docker image
        run: docker push $DOCKER_IMAGE
      - name: Deploy published Docker image
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY}}
          script: |
            docker stop ${{ env.DOCKER_NAME }}
            docker rm -f ${{ env.DOCKER_NAME }}
            docker run --name ${{ env.DOCKER_NAME }} -d -p 80:8000 ${{ env.DOCKER_IMAGE }}
      - name: Verify deployment was successful
        uses: jtalk/url-health-check-action@v4
        with:
          url: http://${{ secrets.HOST_IP }}
          max-attempts: 3 # Optional, defaults to 1
          retry-delay: 5s # Optional, only applicable to max-attempts > 1
          retry-all: false # Optional, defaults to "false"
        
