name: Deploy

on:
  push:
    branches: [main]

env:
  DIRECTORY: zone-blitz
  DOCKER_IMAGE: brendantierney/zone-blitz:latest
  DOCKER_NAME: zone-blitz

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t $DOCKER_IMAGE .
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish Docker image
        run: docker push $DOCKER_IMAGE
      - name: Deploy published Docker image
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY}}
          script: |
            wget -O docker-compose.yml https://raw.githubusercontent.com/Tiernebre/zone-blitz/main/docker-compose.yml
            docker-compose pull
            docker-compose down || echo 'no existing docker image'
            docker-compose up -d
      - name: Verify deployment was successful
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://zoneblitz.app
          max-attempts: 3
          retry-delay: 5s
