name: Test

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  PORT: 8000
  WEB_SERVER_URL: http://127.0.0.1:8000
  URL: https://dev.zoneblitz.app
  TERM: dumb
  ZONE_BLITZ_WEB_DOCKER_IMAGE: brendantierney/zone-blitz:staging
  ZONE_BLITZ_DOMAIN: "0.0.0.0"

jobs:
  application-tests:
    name: Application Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run application tests in development container
        uses: devcontainers/ci@v0.3
        with:
          runCmd: make test

  e2e-test:
    name: E2E Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t $ZONE_BLITZ_WEB_DOCKER_IMAGE .
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish Docker image
        run: docker push $ZONE_BLITZ_WEB_DOCKER_IMAGE
      - name: Run full application stack
        run: docker-compose up -d --wait

  development-environment-smoke-test:
    name: Development Environment Smoke Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run initialize command
        run: .devcontainer/initializeCommand.sh
      - name: Create and start development containers
        run: docker-compose -f .devcontainer/docker-compose.devcontainer.yml up -d
      - name: Start web server in its development container
        run: docker-compose -f .devcontainer/docker-compose.devcontainer.yml exec -T -w /workspace web make &
      - name: Verify development container proxy runs and proxies to web server
        uses: jtalk/url-health-check-action@v4
        with:
          url: ${{ env.URL }}/api/health
          max-attempts: 12
          retry-delay: 5s
          retry-all: true

  verify-codegen:
    name: Verify Generated Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Verify there is no difference in generated code
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            git config --global --add safe.directory /workspace
            git status -s
            git add . && git diff --quiet && git diff --cached --quiet
