name: Test

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  TERM: dumb

jobs:
  application-tests:
    name: Application Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run application tests in development container
        uses: devcontainers/ci@v0.3
        with:
          runCmd: make test

  e2e-staging-test:
    name: E2E Staging Test
    runs-on: ubuntu-latest
    env:
      ZONE_BLITZ_WEB_DOCKER_IMAGE: brendantierney/zone-blitz:staging
      ZONE_BLITZ_DOMAIN: 0.0.0.0
      ZONE_BLITZ_URL: https://${ZONE_BLITZ_DOMAIN}
      CURL: curl -fkv ${ZONE_BLITZ_URL}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Building staging Docker image
        run: docker build -t $ZONE_BLITZ_WEB_DOCKER_IMAGE .
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish staging Docker image
        run: docker push $ZONE_BLITZ_WEB_DOCKER_IMAGE
      - name: Run full application stack in staging mode
        env:
          ZONE_BLITZ_POSTGRES_USER: e2e_staging_test
          ZONE_BLITZ_POSTGRES_PASSWORD: e2e_staging_test
          ZONE_BLITZ_POSTGRES_NAME: zone_blitz
          ZONE_BLITZ_POSTGRES_HOST: database:5432/zone_blitz
        run: docker compose up -d --wait
      - name: Verify application is running and healthy
        run: |
          ${{ env.CURL }} 
          ${{ env.CURL }}/api/health
          ${{ env.CURL }}/favicon.ico

  development-environment-smoke-test:
    name: Development Environment Smoke Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run initialize command
        run: .devcontainer/initializeCommand.sh
      - name: Create and start development containers
        run: docker compose -f .devcontainer/docker-compose.devcontainer.yml up -d
      - name: Start web server in its development container
        run: docker compose -f .devcontainer/docker-compose.devcontainer.yml exec -T -w /workspace web make &
      - name: Verify development container proxy runs and proxies to web server
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://dev.zoneblitz.app/api/health
          max-attempts: 12
          retry-delay: 5s
          retry-all: true

  verify-codegen:
    name: Verify Generated Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Verify there is no difference in generated code
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            git config --global --add safe.directory /workspace
            git status -s
            git add . && git diff --quiet && git diff --cached --quiet
