name: Test

on: push
  
env:
  PORT: 8000
  URL: http://127.0.0.1:8000

jobs:
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run unit tests in development container
        uses: devcontainers/ci@v0.3
        with:
          runCmd: make test

  smoke-test:
    name: Smoke Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t brendantierney/zone-blitz:latest .
      - name: Run Docker image
        run: docker run -d -p $PORT:$PORT brendantierney/zone-blitz:latest
      - name: Verify app runs and serves healthy responses
        uses: jtalk/url-health-check-action@v4
        with:
          url: ${{ env.URL }}|${{ env.URL }}/assets/htmx.js|${{ env.URL }}/assets/styles.css
          max-attempts: 10
          retry-delay: 5s
          retry-all: true
