name: Test

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and run Dev Container for testing
        uses: devcontainers/ci@v0.3
        with:
          runCmd: make test

  test-docker:
    name: Test Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t brendantierney/zone-blitz:latest .
      - name: Run Docker image
        run: docker run -d -p 8000:8000 brendantierney/zone-blitz:latest
      - name: Verify image runs with correct assets
        uses: jtalk/url-health-check-action@v4
        with:
          url: http://127.0.0.1:8000|http://127.0.0.1:8000/assets/htmx.js|http://127.0.0.1:8000/assets/styles.css
          max-attempts: 10
          retry-delay: 5s
          retry-all: true
