name: Test

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  PORT: 8000
  WEB_SERVER_URL: http://127.0.0.1:8000
  URL: https://dev.zoneblitz.app
  TERM: dumb

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run unit tests in development container
        uses: devcontainers/ci@v0.3
        with:
          runCmd: make test

  web-server-test:
    name: Web Server Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Web Server Docker image
        run: docker build -t brendantierney/zone-blitz:latest .
      - name: Run Web Server Docker container
        run: |
          docker run -d --name web -p $PORT:$PORT brendantierney/zone-blitz:latest
          until [ "$(docker inspect -f "{{.State.Health.Status}}" web)" == "healthy" ]; do     sleep 0.1; done;
      - name: Verify web server container runs and serves healthy responses
        uses: jtalk/url-health-check-action@v4
        with:
          url: ${{ env.WEB_SERVER_URL }}/api/health|${{ env.WEB_SERVER_URL }}/htmx.js|${{ env.WEB_SERVER_URL }}/styles.css|${{ env.WEB_SERVER_URL }}/robots.txt
          max-attempts: 1
      - name: Audit web page performance and quality
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: |
            ${{ env.WEB_SERVER_URL }}
          configPath: "./.lighthouserc.json"
          runs: 5

  development-environment-smoke-test:
    name: Development Environment Smoke Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run initialize command
        run: .devcontainer/initializeCommand.sh
      - name: Create and start development containers
        run: docker-compose -f .devcontainer/docker-compose.devcontainer.yml up -d
      - name: Start web server in its development container
        run: docker-compose -f .devcontainer/docker-compose.devcontainer.yml exec -T -w /workspace web make &
      - name: Verify development container proxy runs and proxies to web server
        uses: jtalk/url-health-check-action@v4
        with:
          url: ${{ env.URL }}/api/health
          max-attempts: 12
          retry-delay: 5s
          retry-all: true

  verify-codegen:
    name: Verify Generated Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Verify there is no difference in generated code
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            git config --global --add safe.directory /workspace
            git status -s
            git add . && git diff --quiet && git diff --cached --quiet
