name: Test

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  TERM: dumb

jobs:
  application-tests:
    name: Application Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run application tests in development container
        uses: devcontainers/ci@v0.3
        with:
          runCmd: make test

  e2e-staging-smoke-test:
    name: E2E Staging Smoke Test
    runs-on: ubuntu-latest
    env:
      ZONE_BLITZ_WEB_DOCKER_IMAGE: brendantierney/zone-blitz:staging
      ZONE_BLITZ_DOMAIN: localhost
      ZONE_BLITZ_URL: https://localhost
      CURL: curl --retry 15 --retry-delay 1 --retry-all-errors -fkv https://localhost
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Building staging Docker image
        run: docker build -t $ZONE_BLITZ_WEB_DOCKER_IMAGE .
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish staging Docker image
        run: docker push $ZONE_BLITZ_WEB_DOCKER_IMAGE
      - name: Run full application stack in staging mode
        env:
          ZONE_BLITZ_POSTGRES_USER: e2e_staging_test
          ZONE_BLITZ_POSTGRES_PASSWORD: e2e_staging_test
          ZONE_BLITZ_POSTGRES_NAME: zone_blitz
          ZONE_BLITZ_POSTGRES_HOST: database:5432/zone_blitz
          ZONE_BLITZ_CONTENT_SECURITY_POLICY: default-src https://localhost
        continue-on-error: true
        run: docker compose up -d --wait
      - name: Verify application is running and healthy
        run: |
          ${{ env.CURL }}
          ${{ env.CURL }}/api/health
          ${{ env.CURL }}/favicon.ico
      - name: Audit web page performance and quality
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: |
            ${{ env.ZONE_BLITZ_URL }}
            ${{ env.ZONE_BLITZ_URL }}/login
            ${{ env.ZONE_BLITZ_URL }}/registration
          configPath: "./.lighthouserc.json"
          runs: 5

  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    env:
      ZONE_BLITZ_URL: https://dev.zoneblitz.app
      NODE_EXTRA_CA_CERTS: .devcontainer/certs/dev.zoneblitz.app.cert
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run initialize command
        run: .devcontainer/initializeCommand.sh
      - name: Create and start development containers
        run: docker compose -f .devcontainer/docker-compose.devcontainer.yml up -d
      - name: Start web server in its development container
        run: docker compose -f .devcontainer/docker-compose.devcontainer.yml exec -T -w /workspace web make &
      - name: Trust self signed SSL certificate
        run: |
          mkdir -p $HOME/.pki/nssdb 
          certutil -d $HOME/.pki/nssdb -N --empty-password
          certutil -d sql:$HOME/.pki/nssdb -A -t "C,," -n dev.zoneblitz.app -i .devcontainer/certs/dev.zoneblitz.app.cert;
      - name: Run E2E tests
        run: |
          npx playwright install --with-deps
          make e2e

  verify-codegen:
    name: Verify Generated Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Verify there is no difference in generated code
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            git config --global --add safe.directory /workspace
            git status -s
            git add . && git diff --quiet && git diff --cached --quiet
